[launcher]
version = 1.0.2
description = Collect audit, directory, usage and cost data from Anthropic Claude Enterprise, OpenAI, Google Gemini (Workspace) and Microsoft 365 Copilot for AI monitoring, governance and security in Splunk.
author = Michael Yeack, Manan Grover

[id]
version = 1.0.2
name = TA-ai-governance

[install]
build = 1784668132
is_configured = false
state = enabled

[package]
id = TA-ai-governance
check_for_updates = false

[ui]
label = Enterprise AI Governance App for Splunk
supported_themes = light, dark
is_visible = true

[triggers]
reload.ta-ai-governance_settings = simple
reload.ta-ai-governance_account = simple
