[aigov_audit_events]
search = `aigov_audit`
#description = Audit events from all AI providers

[aigov_authentication_events]
search = `aigov_audit` `aigov_signin_actions`
#description = Sign-in events across AI providers

[aigov_admin_change_events]
search = `aigov_audit` `aigov_admin_actions`
#description = Administrative changes across AI providers

[aigov_usage_events]
search = `aigov_usage`
#description = Usage metrics from all AI providers

[aigov_cost_events]
search = `aigov_cost`
#description = Cost metrics from AI providers
